# fly.toml app configuration file generated for restless-sky-4317 on 2023-06-10T09:18:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-sky-4317"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
